/* Auto-generated by genmsg_cpp for file /home/marco/fuerte_workspace/tbots_vision_pkg/feature_extraction/msg/ObjectFeatureMsg.msg */
#ifndef FEATURE_EXTRACTION_MESSAGE_OBJECTFEATUREMSG_H
#define FEATURE_EXTRACTION_MESSAGE_OBJECTFEATUREMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "feature_extraction/CvSURFPoint.h"
#include "sensor_msgs/Image.h"

namespace feature_extraction
{
template <class ContainerAllocator>
struct ObjectFeatureMsg_ {
  typedef ObjectFeatureMsg_<ContainerAllocator> Type;

  ObjectFeatureMsg_()
  : features()
  , image()
  {
  }

  ObjectFeatureMsg_(const ContainerAllocator& _alloc)
  : features(_alloc)
  , image(_alloc)
  {
  }

  typedef std::vector< ::feature_extraction::CvSURFPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::feature_extraction::CvSURFPoint_<ContainerAllocator> >::other >  _features_type;
  std::vector< ::feature_extraction::CvSURFPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::feature_extraction::CvSURFPoint_<ContainerAllocator> >::other >  features;

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
   ::sensor_msgs::Image_<ContainerAllocator>  image;


  typedef boost::shared_ptr< ::feature_extraction::ObjectFeatureMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::feature_extraction::ObjectFeatureMsg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ObjectFeatureMsg
typedef  ::feature_extraction::ObjectFeatureMsg_<std::allocator<void> > ObjectFeatureMsg;

typedef boost::shared_ptr< ::feature_extraction::ObjectFeatureMsg> ObjectFeatureMsgPtr;
typedef boost::shared_ptr< ::feature_extraction::ObjectFeatureMsg const> ObjectFeatureMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::feature_extraction::ObjectFeatureMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::feature_extraction::ObjectFeatureMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace feature_extraction

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::feature_extraction::ObjectFeatureMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::feature_extraction::ObjectFeatureMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::feature_extraction::ObjectFeatureMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "59ec07cffbe2954664bbdcfb414ab07f";
  }

  static const char* value(const  ::feature_extraction::ObjectFeatureMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x59ec07cffbe29546ULL;
  static const uint64_t static_value2 = 0x64bbdcfb414ab07fULL;
};

template<class ContainerAllocator>
struct DataType< ::feature_extraction::ObjectFeatureMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "feature_extraction/ObjectFeatureMsg";
  }

  static const char* value(const  ::feature_extraction::ObjectFeatureMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::feature_extraction::ObjectFeatureMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CvSURFPoint[] features\n\
sensor_msgs/Image image\n\
\n\
================================================================================\n\
MSG: feature_extraction/CvSURFPoint\n\
# This message contains the same information as a CvSURFPoint from OpenCV2\n\
\n\
#fields for CvSURFPoint\n\
\n\
CvPoint2D32f pt\n\
\n\
# -1, 0 or +1. sign of the laplacian at the point.\n\
int32 laplacian \n\
\n\
# size of the feature\n\
int32 size \n\
\n\
# orientation of the feature: 0..360 degrees\n\
float32 dir \n\
\n\
# value of the hessian (can be used to\n\
# approximately estimate the feature strengths;\n\
# see also params.hessianThreshold)\n\
float32 hessian \n\
\n\
\n\
================================================================================\n\
MSG: feature_extraction/CvPoint2D32f\n\
float32 x\n\
float32 y\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in src/image_encodings.cpp\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::feature_extraction::ObjectFeatureMsg_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::feature_extraction::ObjectFeatureMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.features);
    stream.next(m.image);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ObjectFeatureMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::feature_extraction::ObjectFeatureMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::feature_extraction::ObjectFeatureMsg_<ContainerAllocator> & v) 
  {
    s << indent << "features[]" << std::endl;
    for (size_t i = 0; i < v.features.size(); ++i)
    {
      s << indent << "  features[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::feature_extraction::CvSURFPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.features[i]);
    }
    s << indent << "image: ";
s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
  }
};


} // namespace message_operations
} // namespace ros

#endif // FEATURE_EXTRACTION_MESSAGE_OBJECTFEATUREMSG_H

